using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Text;
using System.Linq;

namespace AdventOfCode.SourceGenerators;

/// <summary>
/// Source generator that automatically generates IParsable&lt;T&gt; boilerplate methods
/// for types marked with [GenerateIParsable] attribute.
/// Supports both non-generic and generic types with IParsable&lt;T&gt; constraints.
/// </summary>
[Generator]
public class ParsableGenerator : IIncrementalGenerator
{
	private const string AttributeName = "AdventOfCode.SourceGenerators.GenerateIParsableAttribute";

	private const string AttributeSource = """
		// <auto-generated/>
		#nullable enable

		namespace AdventOfCode.SourceGenerators;

		/// <summary>
		/// Marks a type for automatic generation of IParsable&lt;T&gt; boilerplate methods.
		/// The type must implement Parse(string s, IFormatProvider? provider).
		/// The generator will create Parse(string s) and TryParse(...) methods automatically.
		/// The generator will add the IParsable&lt;T&gt; interface to the type as well.
		/// For generic types, all type parameters must be constrained to IParsable&lt;T&gt;.
		/// </summary>
		[global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct, Inherited = false, AllowMultiple = false)]
		internal sealed class GenerateIParsableAttribute : global::System.Attribute
		{
			/// <summary>
			/// Gets or sets the characters to use for splitting the input string when multiple constructor parameters exist.
			/// Default is ' ' and ','.
			/// </summary>
			public string SplitChars { get; set; } = " ,";

			/// <summary>
			/// Gets or sets the regex pattern to use for splitting the input string.
			/// If specified, this takes precedence over SplitChars.
			/// </summary>
			[global::System.Diagnostics.CodeAnalysis.StringSyntax("Regex")]
			public string? SplitPattern { get; set; }

			/// <summary>
			/// Gets or sets whether to remove empty entries after splitting.
			/// Default is true.
			/// </summary>
			public bool RemoveEmptyEntries { get; set; } = true;

			/// <summary>
			/// Gets or sets the regex pattern with named capture groups for parsing complex multi-parameter scenarios.
			/// Named groups should match constructor parameter names.
			/// Example: @"(?<Name>\w+):\s*(?<Values>[\d,\s]+)"
			/// When specified, this takes precedence over simple splitting.
			/// </summary>
			[global::System.Diagnostics.CodeAnalysis.StringSyntax("Regex")]
			public string? CapturePattern { get; set; }
		}
		""";

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		// Generate the attribute itself so the generator is self-contained
		context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
			"GenerateIParsableAttribute.g.cs",
			SourceText.From(AttributeSource, Encoding.UTF8)));

		// Register syntax receiver to find types with [GenerateParsable] attribute
		IncrementalValuesProvider<TypeDeclarationSyntax> typeDeclarations = context.SyntaxProvider
			.CreateSyntaxProvider(
				predicate: static (s, _) => IsSyntaxTargetForGeneration(s),
				transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
			.Where(static m => m is not null)!;

		// Combine with compilation
		IncrementalValueProvider<(Compilation, ImmutableArray<TypeDeclarationSyntax>)> compilationAndTypes
			= context.CompilationProvider.Combine(typeDeclarations.Collect());

		// Generate source
		context.RegisterSourceOutput(compilationAndTypes,
			static (spc, source) => Execute(source.Item1, source.Item2, spc));
	}

	private static bool IsSyntaxTargetForGeneration(SyntaxNode node)
		=> node is TypeDeclarationSyntax { AttributeLists.Count: > 0 };

	private static TypeDeclarationSyntax? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
	{
		TypeDeclarationSyntax typeDeclarationSyntax = (TypeDeclarationSyntax)context.Node;

		foreach (AttributeListSyntax attributeListSyntax in typeDeclarationSyntax.AttributeLists) {
			foreach (AttributeSyntax attributeSyntax in attributeListSyntax.Attributes) {
				if (context.SemanticModel.GetSymbolInfo(attributeSyntax).Symbol is not IMethodSymbol attributeSymbol) {
					continue;
				}

				INamedTypeSymbol attributeContainingTypeSymbol = attributeSymbol.ContainingType;
				string fullName = attributeContainingTypeSymbol.ToDisplayString();

				if (fullName == AttributeName) {
					return typeDeclarationSyntax;
				}
			}
		}

		return null;
	}

	private static void Execute(Compilation compilation, ImmutableArray<TypeDeclarationSyntax> types, SourceProductionContext context)
	{
		if (types.IsDefaultOrEmpty) {
			return;
		}

		foreach (TypeDeclarationSyntax typeDeclaration in types.Distinct()) {
			context.CancellationToken.ThrowIfCancellationRequested();

			SemanticModel semanticModel = compilation.GetSemanticModel(typeDeclaration.SyntaxTree);
			if (semanticModel.GetDeclaredSymbol(typeDeclaration) is not INamedTypeSymbol typeSymbol) {
				continue;
			}

			string namespaceName = typeSymbol.ContainingNamespace.ToDisplayString();
			string typeName = typeSymbol.Name;

			// Extract generic type parameters
			GenericTypeInfo genericInfo = GetGenericTypeInfo(typeSymbol);

			// Extract split configuration from attribute
			SplitConfiguration splitConfig = GetSplitConfiguration(typeDeclaration, semanticModel);

			// Determine the full type keyword(s) - handles "record struct", "record class", "record", "class", "struct"
			string typeKeyword = GetTypeKeyword(typeSymbol);

			// Get containing types (for nested types)
			List<(string Name, string Keyword)> containingTypes = [];
			INamedTypeSymbol? containingType = typeSymbol.ContainingType;
			INamedTypeSymbol containingTypeSymbol = default!;
			while (containingType is not null) {
				string containingKeyword = containingType.TypeKind switch
				{
					TypeKind.Class => "partial class",
					TypeKind.Struct => "partial struct",
					_ => "partial class"
				};

				if (containingType.TypeKind is TypeKind.Class or TypeKind.Struct) {
					containingTypeSymbol = containingType;
				}

				containingTypes.Insert(0, (containingType.Name, containingKeyword));
				containingType = containingType.ContainingType;
			}

			// Get constructor parameter types and names
			string[] constructorParametersList = [.. GetRecordParameterTypes(typeSymbol)];
			(string Name, string Type)[] constructorParameters = [.. GetRecordParameters(typeSymbol)];

			// Check which methods already exist
			bool hasParseMethod = HasParseStringMethod(typeSymbol);
			bool hasParseStringWithProviderMethod = HasParseStringWithProviderMethod(typeSymbol);
			bool hasTryParseMethod = HasTryParseMethod(typeSymbol);
			bool implementsIParsable = ImplementsIParsable(typeSymbol);

			// Skip generation if both methods already exist
			//if (hasParseMethod && hasParseStringWithProviderMethod && hasTryParseMethod && implementsIParsable) {
			//	continue;
			//}

			string source = GenerateSource(namespaceName, typeName, typeKeyword, containingTypes, constructorParametersList, constructorParameters,
				!hasParseMethod, !hasParseStringWithProviderMethod, !hasTryParseMethod, !implementsIParsable, splitConfig, genericInfo);

			// Use full type path for unique filename
			string fileName = containingTypes.Count > 0
				? $"{string.Join(".", containingTypes.Select(t => t.Name))}.{typeName}.g.cs"
				: $"{typeName}.g.cs";

			context.AddSource(fileName, SourceText.From(source, Encoding.UTF8));
		}
	}

	private static string GetTypeKeyword(INamedTypeSymbol typeSymbol)
	{
		// Check if it's a record type (record class or record struct)
		bool isRecord = typeSymbol.IsRecord;
		bool isStruct = typeSymbol.TypeKind == TypeKind.Struct;
		bool isClass = typeSymbol.TypeKind == TypeKind.Class;

		return (isRecord, isStruct, isClass) switch
		{
			(true, true, _) => "record struct",
			(true, _, true) => "record class",
			(true, _, _) => "record",
			(false, true, _) => "struct",
			_ => "class"
		};
	}

	private class SplitConfiguration(string splitChars, string? splitPattern, bool removeEmptyEntries, string? capturePattern)
	{
		public string SplitChars { get; } = splitChars;
		public string? SplitPattern { get; } = splitPattern;
		public bool RemoveEmptyEntries { get; } = removeEmptyEntries;
		public string? CapturePattern { get; } = capturePattern;
	}

	private class GenericTypeInfo(string typeParameters, string typeArguments, string whereConstraints)
	{
		public string TypeParameters { get; } = typeParameters; // <T> or <T, U>
		public string TypeArguments { get; } = typeArguments;   // T or T, U
		public string WhereConstraints { get; } = whereConstraints; // where T : IParsable<T>
		public bool IsGeneric => !string.IsNullOrEmpty(TypeParameters);
	}

	private static GenericTypeInfo GetGenericTypeInfo(INamedTypeSymbol typeSymbol)
	{
		if (!typeSymbol.IsGenericType || typeSymbol.TypeParameters.Length == 0) {
			return new GenericTypeInfo("", "", "");
		}

		string[] typeParamNames = [.. typeSymbol.TypeParameters.Select(tp => tp.Name)];
		string typeParameters = $"<{string.Join(", ", typeParamNames)}>";
		string typeArguments = string.Join(", ", typeParamNames);

		// Build where constraints
		List<string> whereConstraints = [];
		foreach (ITypeParameterSymbol typeParam in typeSymbol.TypeParameters) {
			List<string> constraints = [];

			// Check for existing IParsable<T> constraint
			bool hasParsableConstraint = typeParam.ConstraintTypes.Any(ct =>
				ct is INamedTypeSymbol nts &&
				nts.Name == "IParsable" &&
				nts.IsGenericType &&
				nts.TypeArguments.Length == 1);

			// Always add IParsable<T> constraint since we'll be calling T.Parse
			if (!hasParsableConstraint) {
				constraints.Add($"IParsable<{typeParam.Name}>");
			}

			// Add other constraints
			foreach (ITypeSymbol constraintType in typeParam.ConstraintTypes) {
				if (constraintType is INamedTypeSymbol nts &&
					!(nts.Name == "IParsable" && nts.IsGenericType)) {
					constraints.Add(constraintType.ToDisplayString());
				} else if (constraintType is INamedTypeSymbol nts2 && nts2.Name == "IParsable" && nts2.IsGenericType) {
					constraints.Add($"IParsable<{typeParam.Name}>");
				}
			}

			if (typeParam.HasReferenceTypeConstraint) {
				constraints.Insert(0, "class");
			}

			if (typeParam.HasValueTypeConstraint) {
				constraints.Insert(0, "struct");
			}

			if (typeParam.HasConstructorConstraint) {
				constraints.Add("new()");
			}

			if (constraints.Count > 0) {
				whereConstraints.Add($"where {typeParam.Name} : {string.Join(", ", constraints)}");
			}
		}

		string whereClause = whereConstraints.Count > 0 ? $" {string.Join(" ", whereConstraints)}" : "";

		return new GenericTypeInfo(typeParameters, typeArguments, whereClause);
	}

	private static SplitConfiguration GetSplitConfiguration(TypeDeclarationSyntax typeDeclaration, SemanticModel semanticModel)
	{
		string splitChars = " ,";
		string? splitPattern = null;
		bool removeEmptyEntries = true;
		string? capturePattern = null;

		foreach (AttributeListSyntax attributeListSyntax in typeDeclaration.AttributeLists) {
			foreach (AttributeSyntax attributeSyntax in attributeListSyntax.Attributes) {
				if (semanticModel.GetSymbolInfo(attributeSyntax).Symbol is not IMethodSymbol attributeSymbol) {
					continue;
				}

				if (attributeSymbol.ContainingType.ToDisplayString() != AttributeName) {
					continue;
				}

				// Extract attribute arguments
				if (attributeSyntax.ArgumentList is null) {
					continue;
				}

				foreach (AttributeArgumentSyntax argument in attributeSyntax.ArgumentList.Arguments) {
					string? propertyName = argument.NameEquals?.Name.Identifier.Text;
					if (propertyName is null) {
						continue;
					}

					if (propertyName == "SplitChars" && argument.Expression is LiteralExpressionSyntax splitCharsLiteral) {
						splitChars = splitCharsLiteral.Token.ValueText;
					} else if (propertyName == "SplitPattern" && argument.Expression is LiteralExpressionSyntax splitPatternLiteral) {
						splitPattern = splitPatternLiteral.Token.ValueText;
					} else if (propertyName == "RemoveEmptyEntries" && argument.Expression is LiteralExpressionSyntax removeEmptyLiteral) {
						if (bool.TryParse(removeEmptyLiteral.Token.ValueText, out bool value)) {
							removeEmptyEntries = value;
						}
					} else if (propertyName == "CapturePattern" && argument.Expression is LiteralExpressionSyntax capturePatternLiteral) {
						capturePattern = capturePatternLiteral.Token.ValueText;
					}
				}
			}
		}

		return new SplitConfiguration(splitChars, splitPattern, removeEmptyEntries, capturePattern);
	}

	// Get the types of the properties in the constructor of the containing class/struct/record
	private static IEnumerable<string> GetRecordParameterTypes(INamedTypeSymbol typeSymbol)
	{
		// return record properties needed for new RecordType(param1, param2)
		if (typeSymbol is null || !typeSymbol.IsRecord) {
			return [];
		}

		// For records, look for the primary constructor and get its parameter types
		IMethodSymbol? primaryConstructor = typeSymbol.Constructors
			.FirstOrDefault(c => c.Parameters.Length > 0 && !c.IsImplicitlyDeclared);

		if (primaryConstructor is not null) {
			return primaryConstructor.Parameters
				.Select(p => p.Type.ToDisplayString());
		}

		// Fallback: get public properties (works for positional records)
		return typeSymbol.GetMembers()
			.OfType<IPropertySymbol>()
			.Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic)
			.Select(p => p.Type.ToDisplayString());
	}

	// Get both names and types of constructor parameters
	private static IEnumerable<(string Name, string Type)> GetRecordParameters(INamedTypeSymbol typeSymbol)
	{
		if (typeSymbol is null || !typeSymbol.IsRecord) {
			return [];
		}

		// For records, look for the primary constructor
		IMethodSymbol? primaryConstructor = typeSymbol.Constructors
			.FirstOrDefault(c => c.Parameters.Length > 0 && !c.IsImplicitlyDeclared);

		if (primaryConstructor is not null) {
			return primaryConstructor.Parameters
				.Select(p => (p.Name, p.Type.ToDisplayString()));
		}

		// Fallback: get public properties
		return typeSymbol.GetMembers()
			.OfType<IPropertySymbol>()
			.Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic)
			.Select(p => (p.Name, p.Type.ToDisplayString()));
	}

	private static string GenerateSource(string namespaceName, string typeName, string typeKeyword,
		List<(string Name, string Keyword)> containingTypes, string[] constructorParametersList, (string Name, string Type)[] constructorParameters, bool generateParse, bool generateParseWithProvider, bool generateTryParse, bool addIParsableInterface, SplitConfiguration splitConfig, GenericTypeInfo genericInfo)
	{
		// Build opening declarations for nested types
		StringBuilder containingTypesOpen = new();
		StringBuilder containingTypesClose = new();
		int baseIndent = 0;

		foreach ((string name, string keyword) in containingTypes) {
			_ = containingTypesOpen.AppendLine($"{GetIndent(baseIndent)}{keyword} {name}");
			_ = containingTypesOpen.AppendLine($"{GetIndent(baseIndent)}{{");
			_ = containingTypesClose.Insert(0, $"{GetIndent(baseIndent)}}}");
			_ = containingTypesOpen.AppendLine();
			baseIndent++;
		}

		string indent = GetIndent(baseIndent);
		string typeNameWithGenerics = genericInfo.IsGeneric ? $"{typeName}{genericInfo.TypeParameters}" : typeName;
		string interfaceDeclaration = addIParsableInterface ? $" : IParsable<{typeNameWithGenerics}>" : "";

		string parseMethod = generateParse && generateParseWithProvider
			? $$"""
				{{indent}}	public static {{typeNameWithGenerics}} Parse(string s)
				{{indent}}	{
				{{CreateNewFromConstructorParameters(typeName, constructorParametersList, constructorParameters, splitConfig, indent, genericInfo)}}
				{{indent}}	}
				"""
			: generateParse && !generateParseWithProvider
				? $$"""
					{{indent}}	public static {{typeNameWithGenerics}} Parse(string s) => {{typeName}}.Parse(s, null);
					"""
				: "";

		string parseMethodWithProvider = generateParseWithProvider
			? $$"""
				{{indent}}	public static {{typeNameWithGenerics}} Parse(string s, IFormatProvider? provider) => {{typeNameWithGenerics}}.Parse(s);
				"""
			: "";

		string tryParseMethod = generateTryParse
			? $$"""
				{{indent}}	public static bool TryParse([NotNullWhen(true)] string? s, IFormatProvider? provider, [MaybeNullWhen(false)] out {{typeNameWithGenerics}} result)
				{{indent}}	{
				{{indent}}		if (string.IsNullOrWhiteSpace(s))
				{{indent}}		{
				{{indent}}			result = default;
				{{indent}}			return false;
				{{indent}}		}

				{{indent}}		try
				{{indent}}		{
				{{indent}}			result = {{typeNameWithGenerics}}.Parse(s, provider);
				{{indent}}			return true;
				{{indent}}		}
				{{indent}}		catch
				{{indent}}		{
				{{indent}}			result = default;
				{{indent}}			return false;
				{{indent}}		}
				{{indent}}	}
				"""
			: "";

		string parameterTypesComment = constructorParametersList.Length > 0
			? $$"""{{indent}}	// Parameters: {{string.Join(", ", constructorParametersList)}}"""
			: "";

		// Add necessary using statements based on split configuration and parameter types
		bool needsRegex = !string.IsNullOrEmpty(splitConfig.SplitPattern) || !string.IsNullOrEmpty(splitConfig.CapturePattern);
		bool needsLinq = (constructorParametersList.Length > 1 && needsRegex && splitConfig.RemoveEmptyEntries) || !string.IsNullOrEmpty(splitConfig.CapturePattern);

		// Check if any parameter is a collection type that needs LINQ
		foreach (string paramType in constructorParametersList) {
			if (IsCollectionType(paramType, out string? elementType)) {
				if (elementType != "string") {
					needsLinq = true;
				}
			}
		}

		return $$"""
			// <auto-generated/>
			#nullable enable

			using System.Diagnostics.CodeAnalysis;
			{{(needsRegex ? "using System.Text.RegularExpressions;" : "")}}
			{{(needsLinq ? "using System.Linq;" : "")}}
			namespace {{namespaceName}};

			{{containingTypesOpen}}{{indent}}partial {{typeKeyword}} {{typeNameWithGenerics}}{{interfaceDeclaration}}{{genericInfo.WhereConstraints}}
			{{indent}}{
			{{parameterTypesComment}}
			{{parseMethod}}
			{{parseMethodWithProvider}}
			{{tryParseMethod}}
			{{indent}}}
			{{containingTypesClose}}
			""";
	}

	private static string CreateNewFromConstructorParameters(string typeName, string[] constructorParametersList, (string Name, string Type)[] constructorParameters, SplitConfiguration splitConfig, string indent, GenericTypeInfo genericInfo)
	{
		string typeNameWithGenerics = genericInfo.IsGeneric ? $"{typeName}<{genericInfo.TypeArguments}>" : typeName;

		if (constructorParametersList == null || constructorParametersList.Length == 0) {
			return $"{indent}\t\treturn new();";
		}

		// Check if capture pattern is specified - takes precedence for multi-parameter scenarios
		if (!string.IsNullOrEmpty(splitConfig.CapturePattern)) {
			return GenerateCaptureParsing(typeNameWithGenerics, constructorParameters, splitConfig, indent, genericInfo);
		}

		if (constructorParametersList.Length == 1) {
			string parameterType = constructorParametersList[0];

			// Check if it's a collection type
			if (IsCollectionType(parameterType, out string? elementType)) {
				return GenerateCollectionParsing(typeNameWithGenerics, parameterType, elementType!, splitConfig, indent, genericInfo);
			}

			// Check if parameter type is a generic type parameter (needs IParsable<T>.Parse)
			if (genericInfo.IsGeneric && genericInfo.TypeArguments.Split(',').Select(t => t.Trim()).Contains(parameterType)) {
				return $"{indent}\t\treturn new({parameterType}.Parse(s, null));";
			}

			// Simple single parameter
			string parameter = parameterType switch
			{
				"string" => "s",
				_ => $"{parameterType}.Parse(s)"
			};
			return $"{indent}\t\treturn new({parameter});";
		}

		// Multiple parameters - need to split the input string
		StringBuilder sb = new();

		// Generate split logic
		if (!string.IsNullOrEmpty(splitConfig.SplitPattern)) {
			// Use Regex.Split
			string options = splitConfig.RemoveEmptyEntries ? ", RegexOptions.None" : ", RegexOptions.None";
			_ = sb.AppendLine($"{indent}\t\tstring[] parts = Regex.Split(s, @\"{splitConfig.SplitPattern}\"{options});");
			if (splitConfig.RemoveEmptyEntries) {
				_ = sb.AppendLine($"{indent}\t\tparts = parts.Where(p => !string.IsNullOrWhiteSpace(p)).ToArray();");
			}
		} else {
			// Use string.Split with characters
			string splitCharsArray = string.Join(", ", splitConfig.SplitChars.Select(c => $"'{c}'"));
			string splitOptions = splitConfig.RemoveEmptyEntries
				? ", StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries"
				: ", StringSplitOptions.TrimEntries";
			_ = sb.AppendLine($"{indent}\t\tstring[] parts = s.Split([{splitCharsArray}]{splitOptions});");
		}

		// Generate parameter parsing
		List<string> parameterExpressions = [];
		string[] genericTypeParams = genericInfo.IsGeneric
			? [.. genericInfo.TypeArguments.Split(',').Select(t => t.Trim())]
			: [];

		for (int i = 0; i < constructorParametersList.Length; i++) {
			string parameterType = constructorParametersList[i];

			// Check if this is a generic type parameter
			if (genericTypeParams.Contains(parameterType)) {
				parameterExpressions.Add($"{parameterType}.Parse(parts[{i}], null)");
			} else {
				string expression = parameterType switch
				{
					"string" => $"parts[{i}]",
					_ => $"{parameterType}.Parse(parts[{i}])"
				};
				parameterExpressions.Add(expression);
			}
		}

		_ = sb.Append($"{indent}\t\treturn new {typeNameWithGenerics}({string.Join(", ", parameterExpressions)});");
		return sb.ToString();
	}

	private static bool IsCollectionType(string typeString, out string? elementType)
	{
		elementType = null;

		// Check for array: T[]
		if (typeString.EndsWith("[]")) {
			elementType = typeString.Substring(0, typeString.Length - 2);
			return true;
		}

		// Check for List<T>
		if (typeString.StartsWith("List<") || typeString.StartsWith("System.Collections.Generic.List<")) {
			int startIndex = typeString.IndexOf('<') + 1;
			int endIndex = typeString.LastIndexOf('>');
			if (endIndex > startIndex) {
				elementType = typeString.Substring(startIndex, endIndex - startIndex);
				return true;
			}
		}

		// Check for IEnumerable<T>
		if (typeString.StartsWith("IEnumerable<") || typeString.StartsWith("System.Collections.Generic.IEnumerable<")) {
			int startIndex = typeString.IndexOf('<') + 1;
			int endIndex = typeString.LastIndexOf('>');
			if (endIndex > startIndex) {
				elementType = typeString.Substring(startIndex, endIndex - startIndex);
				return true;
			}
		}

		// Check for HashSet<T>
		if (typeString.StartsWith("HashSet<") || typeString.StartsWith("System.Collections.Generic.HashSet<")) {
			int startIndex = typeString.IndexOf('<') + 1;
			int endIndex = typeString.LastIndexOf('>');
			if (endIndex > startIndex) {
				elementType = typeString.Substring(startIndex, endIndex - startIndex);
				return true;
			}
		}

		return false;
	}

	private static string GenerateCollectionParsing(string typeName, string parameterType, string elementType, SplitConfiguration splitConfig, string indent, GenericTypeInfo genericInfo)
	{
		StringBuilder sb = new();

		// Generate split logic
		if (!string.IsNullOrEmpty(splitConfig.SplitPattern)) {
			// Use Regex.Split
			string options = splitConfig.RemoveEmptyEntries ? ", RegexOptions.None" : ", RegexOptions.None";
			_ = sb.AppendLine($"{indent}\t\tstring[] parts = Regex.Split(s, @\"{splitConfig.SplitPattern}\"{options});");
			if (splitConfig.RemoveEmptyEntries) {
				_ = sb.AppendLine($"{indent}\t\tparts = parts.Where(p => !string.IsNullOrWhiteSpace(p)).ToArray();");
			}
		} else {
			// Use string.Split with characters
			string splitCharsArray = string.Join(", ", splitConfig.SplitChars.Select(c => $"'{c}'"));
			string splitOptions = splitConfig.RemoveEmptyEntries
				? ", StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries"
				: ", StringSplitOptions.TrimEntries";
			_ = sb.AppendLine($"{indent}\t\tstring[] parts = s.Split([{splitCharsArray}]{splitOptions});");
		}

		// Check if element type is a generic type parameter
		string[] genericTypeParams = genericInfo.IsGeneric
			? [.. genericInfo.TypeArguments.Split(',').Select(t => t.Trim())]
			: [];

		// Generate element parsing based on element type
		// For generic type parameters, use IParsable<T>.Parse
		string parseExpression = elementType switch
		{
			"string" => "parts",
			_ when genericTypeParams.Contains(elementType) => $"parts.Select(p => {elementType}.Parse(p, null)).ToArray()",
			_ when IsSimpleTypeName(elementType) => $"parts.Select(p => {elementType}.Parse(p, null)).ToArray()",
			_ => $"parts.Select({elementType}.Parse).ToArray()"
		};

		// Generate collection creation based on parameter type
		string collectionCreation;
		if (parameterType.EndsWith("[]")) {
			// Array type
			collectionCreation = elementType == "string" ? "parts" : parseExpression;
		} else if (parameterType.StartsWith("List<") || parameterType.StartsWith("System.Collections.Generic.List<")) {
			// List<T> type
			collectionCreation = elementType == "string" ? "[.. parts]" : $"[.. {parseExpression}]";
		} else if (parameterType.StartsWith("HashSet<") || parameterType.StartsWith("System.Collections.Generic.HashSet<")) {
			// HashSet<T> type
			collectionCreation = elementType == "string" ? "[.. parts]" : $"[.. {parseExpression}]";
		} else {
			// IEnumerable<T> type
			collectionCreation = elementType == "string" ? "parts" : parseExpression;
		}

		_ = sb.Append($"{indent}\t\treturn new {typeName}({collectionCreation});");
		return sb.ToString();
	}

	private static bool IsSimpleTypeName(string typeName)
	{
		// Check if the type name is a simple identifier (T, U, TValue, etc.) without dots or generic markers
		return !string.IsNullOrEmpty(typeName) &&
			   !typeName.Contains('.') &&
			   !typeName.Contains('<') &&
			   !typeName.Contains('>') &&
			   char.IsUpper(typeName[0]);
	}

	private static string GenerateCaptureParsing(string typeName, (string Name, string Type)[] constructorParameters, SplitConfiguration splitConfig, string indent, GenericTypeInfo genericInfo)
	{
		StringBuilder sb = new();

		// Match validation with descriptive error
		_ = sb.AppendLine($"{indent}\t\tMatch match = Regex.Match(s, @\"{splitConfig.CapturePattern}\");");
		_ = sb.AppendLine($"{indent}\t\tif (!match.Success)");
		_ = sb.AppendLine($"{indent}\t\t{{");
		_ = sb.AppendLine($"{indent}\t\t\tthrow new FormatException($\"Input string '{{s}}' does not match expected pattern.\");");
		_ = sb.AppendLine($"{indent}\t\t}}");
		_ = sb.AppendLine();

		List<string> paramExpressions = [];

		foreach ((string name, string type) in constructorParameters) {
			// Validate capture group exists
			_ = sb.AppendLine($"{indent}\t\tif (!match.Groups[\"{name}\"].Success)");
			_ = sb.AppendLine($"{indent}\t\t{{");
			_ = sb.AppendLine($"{indent}\t\t\tthrow new FormatException($\"Required capture group '{name}' not found in input.\");");
			_ = sb.AppendLine($"{indent}\t\t}}");
			_ = sb.AppendLine();

			// Generate parsing with error context
			if (IsCollectionType(type, out string? elementType)) {
				string varName = $"{name.ToLower()}Value";
				_ = sb.AppendLine($"{indent}\t\tstring {varName} = match.Groups[\"{name}\"].Value;");

				// Collection parsing with element-level error handling
				string parseLogic = GenerateSafeCollectionParsing(name, varName, elementType!, type, splitConfig, indent, genericInfo);
				_ = sb.AppendLine(parseLogic);
				paramExpressions.Add($"{name.ToLower()}Parsed");
			} else {
				string parseExpr = GenerateSafeValueParsing(name, type, indent, genericInfo);
				_ = sb.AppendLine(parseExpr);
				paramExpressions.Add($"{name.ToLower()}Parsed");
			}
		}

		_ = sb.AppendLine();
		_ = sb.Append($"{indent}\t\treturn new {typeName}({string.Join(", ", paramExpressions)});");
		return sb.ToString();
	}

	private static string GenerateSafeValueParsing(string paramName, string paramType, string indent, GenericTypeInfo genericInfo)
	{
		string varName = paramName.ToLower();

		if (paramType == "string") {
			return $"{indent}\t\tstring {varName}Parsed = match.Groups[\"{paramName}\"].Value;";
		}

		// Check if this is a generic type parameter
		string[] genericTypeParams = genericInfo.IsGeneric
			? [.. genericInfo.TypeArguments.Split(',').Select(t => t.Trim())]
			: [];

		StringBuilder sb = new();
		_ = sb.AppendLine($"{indent}\t\t{paramType} {varName}Parsed;");
		_ = sb.AppendLine($"{indent}\t\ttry");
		_ = sb.AppendLine($"{indent}\t\t{{");

		// For generic type parameters, use IParsable<T>.Parse
		if (genericTypeParams.Contains(paramType) || IsSimpleTypeName(paramType)) {
			_ = sb.AppendLine($"{indent}\t\t\t{varName}Parsed = {paramType}.Parse(match.Groups[\"{paramName}\"].Value, null);");
		} else {
			_ = sb.AppendLine($"{indent}\t\t\t{varName}Parsed = {paramType}.Parse(match.Groups[\"{paramName}\"].Value);");
		}

		_ = sb.AppendLine($"{indent}\t\t}}");
		_ = sb.AppendLine($"{indent}\t\tcatch (Exception ex)");
		_ = sb.AppendLine($"{indent}\t\t{{");
		_ = sb.Append($"{indent}\t\t\tthrow new FormatException($\"Failed to parse '{paramName}' value '{{{{match.Groups[\\\"{paramName}\\\"].Value}}}}' as {paramType}.\", ex);");
		_ = sb.AppendLine($"{indent}\t\t}}");
		return sb.ToString();
	}

	private static string GenerateSafeCollectionParsing(string paramName, string valueVar, string elementType, string parameterType, SplitConfiguration splitConfig, string indent, GenericTypeInfo genericInfo)
	{
		StringBuilder sb = new();

		// Split the captured value
		string splitCharsArray = string.Join(", ", splitConfig.SplitChars.Select(c => $"'{c}'"));
		string splitOptions = splitConfig.RemoveEmptyEntries
			? "StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries"
			: "StringSplitOptions.TrimEntries";

		_ = sb.AppendLine($"{indent}\t\tstring[] {valueVar}Parts = {valueVar}.Split([{splitCharsArray}], {splitOptions});");

		string varName = paramName.ToLower();

		if (elementType == "string") {
			// Determine collection type for string elements
			string collectionCreation;
			if (parameterType.EndsWith("[]")) {
				collectionCreation = $"{valueVar}Parts";
			} else if (parameterType.StartsWith("List<") || parameterType.StartsWith("System.Collections.Generic.List<")) {
				collectionCreation = $"[.. {valueVar}Parts]";
			} else if (parameterType.StartsWith("HashSet<") || parameterType.StartsWith("System.Collections.Generic.HashSet<")) {
				collectionCreation = $"[.. {valueVar}Parts]";
			} else {
				collectionCreation = $"{valueVar}Parts";
			}
			_ = sb.Append($"{indent}\t\t{GetCollectionTypeForVariable(parameterType, elementType)} {varName}Parsed = {collectionCreation};");
			return sb.ToString();
		}

		// Check if element type is a generic type parameter
		string[] genericTypeParams = genericInfo.IsGeneric
			? [.. genericInfo.TypeArguments.Split(',').Select(t => t.Trim())]
			: [];

		// Parse with error handling for each element
		_ = sb.AppendLine($"{indent}\t\tList<{elementType}> {varName}List = [];");
		_ = sb.AppendLine($"{indent}\t\tfor (int i = 0; i < {valueVar}Parts.Length; i++)");
		_ = sb.AppendLine($"{indent}\t\t{{");
		_ = sb.AppendLine($"{indent}\t\t\ttry");
		_ = sb.AppendLine($"{indent}\t\t\t{{");

		// For generic type parameters, use IParsable<T>.Parse
		if (genericTypeParams.Contains(elementType) || IsSimpleTypeName(elementType)) {
			_ = sb.AppendLine($"{indent}\t\t\t\t{varName}List.Add({elementType}.Parse({valueVar}Parts[i], null));");
		} else {
			_ = sb.AppendLine($"{indent}\t\t\t\t{varName}List.Add({elementType}.Parse({valueVar}Parts[i]));");
		}

		_ = sb.AppendLine($"{indent}\t\t\t}}");
		_ = sb.AppendLine($"{indent}\t\t\tcatch (Exception ex)");
		_ = sb.AppendLine($"{indent}\t\t\t{{");
		_ = sb.AppendLine($"{indent}\t\t\t\tthrow new FormatException($\"Failed to parse '{paramName}[{{i}}]' value '{{{valueVar}Parts[i]}}' as {elementType}.\", ex);");
		_ = sb.AppendLine($"{indent}\t\t\t}}");
		_ = sb.AppendLine($"{indent}\t\t}}");

		// Create appropriate collection type
		if (parameterType.EndsWith("[]")) {
			_ = sb.Append($"{indent}\t\t{elementType}[] {varName}Parsed = [.. {varName}List];");
		} else if (parameterType.StartsWith("List<") || parameterType.StartsWith("System.Collections.Generic.List<")) {
			_ = sb.Append($"{indent}\t\tList<{elementType}> {varName}Parsed = {varName}List;");
		} else if (parameterType.StartsWith("HashSet<") || parameterType.StartsWith("System.Collections.Generic.HashSet<")) {
			_ = sb.Append($"{indent}\t\tHashSet<{elementType}> {varName}Parsed = [.. {varName}List];");
		} else {
			_ = sb.Append($"{indent}\t\tIEnumerable<{elementType}> {varName}Parsed = {varName}List;");
		}

		return sb.ToString();
	}

	private static string GetCollectionTypeForVariable(string parameterType, string elementType)
	{
		if (parameterType.EndsWith("[]")) {
			return $"{elementType}[]";
		} else if (parameterType.StartsWith("List<") || parameterType.StartsWith("System.Collections.Generic.List<")) {
			return $"List<{elementType}>";
		} else if (parameterType.StartsWith("HashSet<") || parameterType.StartsWith("System.Collections.Generic.HashSet<")) {
			return $"HashSet<{elementType}>";
		} else {
			return $"IEnumerable<{elementType}>";
		}
	}

	private static string GetIndent(int level) => new('\t', level);

	private static bool HasParseStringMethod(INamedTypeSymbol typeSymbol)
	{
		return typeSymbol.GetMembers("Parse")
			.OfType<IMethodSymbol>()
			.Any(m => m.IsStatic &&
				 m.Parameters.Length == 1 &&
				 m.Parameters[0].Type.SpecialType == SpecialType.System_String);
	}

	private static bool HasParseStringWithProviderMethod(INamedTypeSymbol typeSymbol)
	{
		return typeSymbol.GetMembers("Parse")
			.OfType<IMethodSymbol>()
			.Any(m => m.IsStatic &&
				 m.Parameters.Length == 2 &&
				 m.Parameters[0].Type.SpecialType == SpecialType.System_String);
	}

	private static bool HasTryParseMethod(INamedTypeSymbol typeSymbol)
	{
		return typeSymbol.GetMembers("TryParse")
			.OfType<IMethodSymbol>()
			.Any(m => m.IsStatic &&
				 m.Parameters.Length == 3 &&
				 m.Parameters[0].Type.SpecialType == SpecialType.System_String &&
				 m.Parameters[2].RefKind == RefKind.Out);
	}

	private static bool ImplementsIParsable(INamedTypeSymbol typeSymbol)
	{
		return typeSymbol.AllInterfaces.Any(i =>
			i.Name == "IParsable" &&
			i.IsGenericType &&
			i.TypeArguments.Length == 1);
	}
}
