using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

using System.Text;

namespace AdventOfCode.SourceGenerators;

/// <summary>
/// Source generator that automatically generates test output helper boilerplate
/// for test classes marked with [SupportTestOutput] attribute.
/// </summary>
[Generator]
public class TestOutputGenerator : IIncrementalGenerator
{
	private const string AttributeName = "AdventOfCode.SourceGenerators.SupportTestOutputAttribute";

	private const string AttributeSource = """
		// <auto-generated/>
		#nullable enable

		namespace AdventOfCode.SourceGenerators;

		/// <summary>
		/// Marks a test class for automatic generation of ITestOutputHelper boilerplate.
		/// The generator will add the ITestOutputHelper parameter to the constructor
		/// and generate a Callback method for test output visualization.
		/// </summary>
		[global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
		internal sealed class SupportTestOutputAttribute : global::System.Attribute
		{
		}
		""";

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		// Generate the attribute itself so the generator is self-contained
		context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
			"SupportTestOutputAttribute.g.cs",
			SourceText.From(AttributeSource, Encoding.UTF8)));

		// Use ForAttributeWithMetadataName for efficient attribute lookup
		IncrementalValuesProvider<GeneratorAttributeSyntaxContext> classDeclarations = context.SyntaxProvider
			.ForAttributeWithMetadataName(
				fullyQualifiedMetadataName: AttributeName,
				predicate: static (node, _) => node is ClassDeclarationSyntax,
				transform: static (context, _) => context);

		// Generate source
		context.RegisterSourceOutput(classDeclarations,
			static (spc, source) => Execute(source, spc));
	}

	private static void Execute(GeneratorAttributeSyntaxContext context, SourceProductionContext sourceContext)
	{
		sourceContext.CancellationToken.ThrowIfCancellationRequested();

		if (context.TargetSymbol is not INamedTypeSymbol classSymbol) {
			return;
		}

		string namespaceName = classSymbol.ContainingNamespace.ToDisplayString();
		string className = classSymbol.Name;

		// Check if constructor already has ITestOutputHelper parameter
		bool hasTestOutputHelperParameter = HasTestOutputHelperParameter(classSymbol);

		// Check if Callback method already exists
		bool hasCallbackMethod = HasCallbackMethod(classSymbol);

		// Skip generation if both already exist
		if (hasTestOutputHelperParameter && hasCallbackMethod) {
			return;
		}

		string source = GenerateSource(
			namespaceName,
			className,
			!hasTestOutputHelperParameter,
			!hasCallbackMethod);

		sourceContext.AddSource($"{className}.TestOutput.g.cs", SourceText.From(source, Encoding.UTF8));
	}

	private static string GenerateSource(
		string namespaceName,
		string className,
		bool generateConstructorParameter,
		bool generateCallbackMethod)
	{
		string constructorParameter = generateConstructorParameter
			? "(ITestOutputHelper _testOutputHelper)"
			: "";

		string callbackMethod = generateCallbackMethod
			? """

					private void Callback(string[] lines, bool _)
					{
						if (lines is null or [])
						{
							return;
						}

						_testOutputHelper.WriteLine(string.Join(Environment.NewLine, lines));
					}
				"""
			: "";

		string helperMethods = """

				/// <summary>
				/// Helper method that wraps SolutionRouter.SolveProblem with automatic Callback injection.
				/// </summary>
				protected string SolveProblem(int year, int day, int problemNo, string? input, params object[]? args)
					=> AdventOfCode.Solutions.SolutionRouter.SolveProblem(year, day, problemNo, input, new Action<string[], bool>(Callback), args);

				/// <summary>
				/// Helper method that wraps SolutionRouter.SolveProblem with automatic Callback injection.
				/// </summary>
				protected string SolveProblem(int year, int day, int problemNo, string[]? input, params object[]? args)
					=> AdventOfCode.Solutions.SolutionRouter.SolveProblem(year, day, problemNo, input, new Action<string[], bool>(Callback), args);
			""";

		return $$"""
			// <auto-generated/>
			#nullable enable

			namespace {{namespaceName}};

			partial class {{className}}{{constructorParameter}}
			{
			{{callbackMethod}}
			{{helperMethods}}
			}
			""";
	}

	private static bool HasTestOutputHelperParameter(INamedTypeSymbol classSymbol)
	{
		return classSymbol.Constructors
			.Where(c => !c.IsStatic)
			.SelectMany(constructor => constructor.Parameters)
			.Any(parameter => parameter.Type.Name == "ITestOutputHelper");
	}

	private static bool HasCallbackMethod(INamedTypeSymbol classSymbol)
	{
		return classSymbol.GetMembers("Callback")
			.OfType<IMethodSymbol>()
			.Any();
	}
}
