namespace AdventOfCode.Tests.Year2025;

[SupportTestOutput]
public partial class Tests_07_Laboratories
{
	const int DAY = 07;

	private const string TEST_DATA =
		"""
		.......S.......
		...............
		.......^.......
		...............
		......^.^......
		...............
		.....^.^.^.....
		...............
		....^.^...^....
		...............
		...^.^...^.^...
		...............
		..^...^.....^..
		...............
		.^.^.^.^.^...^.
		...............
		""";

	[Theory]
	[InlineData(TEST_DATA, 21)]
	public void Part1(string input, int expected)
	{
		input = input.Replace('.', ' ');
		_ = int.TryParse(SolveProblem(YEAR, DAY, PART1, input), out int actual);
		actual.ShouldBe(expected);
	}
}
